/**
 * Downloads and uses upstream Anon Aadhaar test signing material to build
 * our own test QR data (and, from it, real proofs).
 *
 * None of this is committed. `.cache/` is gitignored; every file here is
 * fetched at test/script-run time from the anon-aadhaar/anon-aadhaar GitHub
 * repo, pinned to a fixed commit and verified by sha256 before use (see
 * FIXTURE_FILES below). This is upstream's own published test key --
 * generated by them for exactly this purpose (letting third parties build
 * synthetic Aadhaar QR codes for testing) -- not a secret of ours, but it
 * still must never land in a tracked file (graded test case 8), hence the
 * gitignored cache instead of a checked-in copy.
 */
import { createHash, createSign } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const REPO = "anon-aadhaar/anon-aadhaar";
const PINNED_COMMIT = "4dad918761cfb1d7d5ed9918dcd796d0cb23ae82";
const CACHE_DIR = path.join(process.cwd(), ".cache", "anon-aadhaar-fixtures", PINNED_COMMIT);

type FixtureFile = {
  repoPath: string;
  localName: string;
  sha256: string;
};

// sha256 pins computed once from a known-good download of each file at
// PINNED_COMMIT (see NOTES-FOR-REVIEW.md for how to recompute/verify).
const FIXTURE_FILES: FixtureFile[] = [
  {
    repoPath: "packages/circuits/assets/testCertificate.pem",
    localName: "testCertificate.pem",
    sha256: "a025f6e83f50885299d91a881ab667fe08aa8206062ea560e81d06a59bfdaae6",
  },
  {
    repoPath: "packages/circuits/assets/testPrivateKey.pem",
    localName: "testPrivateKey.pem",
    sha256: "b442d1b4b4b848be9657c7dd984ddce8267a72e5e170d8bfcb8a9fd711403640",
  },
  {
    repoPath: "packages/circuits/scripts/generateTestData.ts",
    localName: "generateTestData.ts",
    sha256: "d1e474637a9bf79876a54ab3e64ca7c9b2b1933edfdb7354ff5491a3473f8ea4",
  },
];

function sha256Hex(data: Buffer): string {
  return createHash("sha256").update(data).digest("hex");
}

async function fetchAndVerify(file: FixtureFile): Promise<string> {
  const dest = path.join(CACHE_DIR, file.localName);

  if (existsSync(dest)) {
    const existing = await readFile(dest);
    if (sha256Hex(existing) === file.sha256) {
      return dest;
    }
  }

  const url = `https://raw.githubusercontent.com/${REPO}/${PINNED_COMMIT}/${file.repoPath}`;
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`failed to fetch ${url}: ${res.status} ${res.statusText}`);
  }
  const buf = Buffer.from(await res.arrayBuffer());
  const actualSha256 = sha256Hex(buf);
  if (actualSha256 !== file.sha256) {
    throw new Error(
      `sha256 mismatch for ${file.repoPath}: got ${actualSha256}, expected ${file.sha256}`,
    );
  }

  await mkdir(CACHE_DIR, { recursive: true });
  await writeFile(dest, buf);
  return dest;
}

export async function ensureFixtures(): Promise<{
  certificatePath: string;
  privateKeyPath: string;
  generateTestDataPath: string;
}> {
  const [certificatePath, privateKeyPath, generateTestDataPath] = await Promise.all(
    FIXTURE_FILES.map(fetchAndVerify),
  );
  return { certificatePath, privateKeyPath, generateTestDataPath };
}

/** Extracts the base (V1-format, already-signed-by-UIDAI-test-key) Aadhaar
 * test data blob embedded as a literal in upstream's own
 * generateTestData.ts script. This is the same "official test data issued
 * by the UIDAI" upstream itself uses as the seed for every synthetic test
 * QR it produces. */
async function readBaseV1Data(generateTestDataPath: string): Promise<string> {
  const src = await readFile(generateTestDataPath, "utf8");
  const match = src.match(/const data =\s*\n?\s*'([0-9]+)'/);
  if (!match) {
    throw new Error("could not locate base V1 test data constant in generateTestData.ts");
  }
  return match[1]!;
}

export type TestQrOverrides = {
  dob?: string; // DD-MM-YYYY
  pincode?: string;
  gender?: string;
  state?: string;
};

/**
 * Builds a freshly-signed V2-format Aadhaar test QR data string (the exact
 * decimal string the real app's QR scanner reads), optionally overriding
 * dob/pincode/gender/state -- e.g. `{ dob: "01-01-2015" }` for a minor, used
 * by the NOT_ELIGIBLE test case. Signed with upstream's own test private
 * key, so it verifies against `testPublicKeyHash` exactly like a real
 * (test-mode) Aadhaar QR would.
 */
export async function buildTestQrData(overrides: TestQrOverrides = {}): Promise<string> {
  const core = await import("@anon-aadhaar/core");
  const { certificatePath, privateKeyPath, generateTestDataPath } = await ensureFixtures();

  const baseData = await readBaseV1Data(generateTestDataPath);
  const privateKey = await readFile(privateKeyPath, "utf8");

  const qrBytes = core.convertBigIntToByteArray(BigInt(baseData));
  const decoded = core.decompressByteArray(qrBytes);
  const signedData = decoded.slice(0, decoded.length - 256);

  const newSignedData = core.createCustomV2TestData({
    signedData,
    dob: overrides.dob,
    pincode: overrides.pincode,
    gender: overrides.gender,
    state: overrides.state,
  });

  const sign = createSign("sha256");
  sign.update(Buffer.from(newSignedData));
  sign.end();
  const signature = sign.sign({ key: privateKey });

  const full = Buffer.concat([Buffer.from(newSignedData), signature]);
  const compressedBigInt = core.rawDataToCompressedQR(full);

  // Certificate isn't used here, but ensureFixtures already downloaded and
  // verified it -- callers needing it (generateArgs) read it separately via
  // getCertificatePem() below.
  void certificatePath;

  return compressedBigInt.toString();
}

export async function getCertificatePem(): Promise<string> {
  const { certificatePath } = await ensureFixtures();
  return readFile(certificatePath, "utf8");
}
