import { randomUUID } from "node:crypto";
import { Client } from "pg";
import { afterAll, describe, expect, inject, it } from "vitest";
import { generateTestProof } from "../../scripts/lib/generateProof";
import { baseUrl, createDraft, loginVolunteer, submitApplication } from "./lib/helpers";

// Every proof here is REAL: generated by the actual anon-aadhaar circuit
// (via generateTestProof, which uses our public/ zk artifacts and
// upstream's own test signing key -- see scripts/lib/testFixtures.ts), not
// mocked, not hardcoded, not read from a committed fixture.
//
// Real proof generation is slow (~35s each standalone -- see
// scripts/bench-proof.ts), so this suite deliberately generates as FEW of
// them as the rubric allows and reuses each one across every assertion the
// underlying property permits:
//   - proofA (default/adult QR): the success path (TC3, TC7), then reused
//     by MUTATING fields for TC2 (wrong seed) and TC5 (signal mismatch),
//     since both of those checks run before groth16 verification even
//     looks at the proof's cryptographic content -- a field mutation
//     produces exactly the input a real proof with that defect would have.
//   - proofB (same QR/identity as proofA, new draft): TC1 duplicate --
//     this one MUST be a fresh real proof, because "same human, new
//     application" is precisely the property under test and can't be
//     faked by mutating proofA.
//   - proofC (minor-DOB QR): TC4 not-eligible.
// The concurrency race (also part of TC1) is covered at the DB level
// instead of with a second pair of real proofs -- see the last test.
describe("recording path (real proofs, over HTTP against a real next start)", () => {
  afterAll(async () => {
    // snarkjs caches its bn128 curve as a worker-thread pool on
    // globalThis.curve_bn128 and never terminates it -- left running, it
    // would keep this vitest worker process alive after the suite finishes.
    const g = globalThis as unknown as { curve_bn128?: { terminate: () => Promise<void> } | null };
    if (g.curve_bn128) await g.curve_bn128.terminate();
  });

  const nullifierSeed = inject("nullifierSeed" as never) as string;

  let firstProof: Awaited<ReturnType<typeof generateTestProof>>;
  let firstDraftId: string;

  it("TC3/TC7: a tampered proof is rejected, and a valid real proof is then accepted", async () => {
    const draft = await createDraft({ preferredName: "Recording Path Success Applicant" });
    const proof = await generateTestProof({ nullifierSeed, signal: draft.signal });

    // Tamper with one field of an otherwise-valid, correctly-bound proof.
    const tampered = {
      ...proof,
      groth16Proof: {
        ...proof.groth16Proof,
        pi_a: [
          (BigInt(proof.groth16Proof.pi_a[0]) + 1n).toString(),
          proof.groth16Proof.pi_a[1],
          proof.groth16Proof.pi_a[2],
        ],
      },
    };
    const tamperedResult = await submitApplication(draft.applicationId, tampered);
    expect(tamperedResult.status).toBe(400);
    expect(tamperedResult.body.error).toBe("INVALID_PROOF");

    // The real, untampered proof for the SAME draft must still work --
    // proves the rejection above was about the tamper, not the draft.
    const okResult = await submitApplication(draft.applicationId, proof);
    expect(okResult.status).toBe(201);
    expect(["anchored", "pending"]).toContain(okResult.body.anchorStatus);

    // Reused below for TC2, TC5, DRAFT_ALREADY_SUBMITTED, and the
    // volunteer-review flow instead of generating new proofs/applications.
    firstProof = proof;
    firstDraftId = draft.applicationId;
  });

  it("TC5: reusing a proof against a different applicationId is rejected as SIGNAL_MISMATCH", async () => {
    const otherDraft = await createDraft();
    const result = await submitApplication(otherDraft.applicationId, firstProof);
    expect(result.status).toBe(400);
    expect(result.body.error).toBe("SIGNAL_MISMATCH");
  });

  it("TC2: a proof whose own nullifierSeed field doesn't match config is rejected as WRONG_SEED", async () => {
    // WRONG_SEED is a plain string comparison against the proof's own
    // nullifierSeed field, checked before pubkeyHash/signal/groth16
    // verification (see src/server/intake/submit.ts step 2) -- so mutating
    // that one field on an already-valid, already-generated proof produces
    // exactly the input a real proof generated with the wrong seed would
    // have, with no new fullProve call.
    const draft = await createDraft();
    const wrongSeed = (BigInt(nullifierSeed) + 1n).toString();
    const mutated = { ...firstProof, nullifierSeed: wrongSeed };

    const result = await submitApplication(draft.applicationId, mutated);
    expect(result.status).toBe(400);
    expect(result.body.error).toBe("WRONG_SEED");
  });

  it("OVER_DISCLOSURE: a proof revealing gender/pincode/state is rejected before verification", async () => {
    // Reuses firstProof (no new real proof) -- mutating one revealed field
    // to a non-"0" value is exactly the shape a hand-crafted/forged payload
    // asking us to publish an Aadhaar-decoded field on-chain would have.
    // src/server/intake/submit.ts checks this before signal comparison or
    // groth16 verification, so the mutation doesn't need to otherwise stay
    // "proof-shaped valid" -- the point is it's rejected before verify ever
    // runs.
    const draft = await createDraft();
    const mutated = { ...firstProof, gender: "1" };
    const result = await submitApplication(draft.applicationId, mutated);
    expect(result.status).toBe(400);
    expect(result.body.error).toBe("OVER_DISCLOSURE");
  });

  it("resubmitting an already-recorded draft is rejected", async () => {
    const result = await submitApplication(firstDraftId, firstProof);
    expect(result.status).toBe(409);
    expect(result.body.error).toBe("DRAFT_ALREADY_SUBMITTED");
  });

  // TC1: one claim per human, enforced by the stored (and on-chain)
  // nullifier -- a second, independently-generated real proof for the
  // SAME underlying identity (same base test QR, same nullifierSeed) is
  // rejected even though it is bound to a brand-new application.
  it("TC1: a second real proof sharing the same nullifier is rejected as DUPLICATE", async () => {
    const draft = await createDraft();
    const proof = await generateTestProof({ nullifierSeed, signal: draft.signal });
    expect(proof.nullifier).toBe(firstProof.nullifier); // sanity: same underlying human

    const result = await submitApplication(draft.applicationId, proof);
    expect(result.status).toBe(409);
    expect(result.body.error).toBe("DUPLICATE");
  });

  it("TC4: a QR generated with a minor's dob is rejected as NOT_ELIGIBLE", async () => {
    const draft = await createDraft();
    const proof = await generateTestProof({
      nullifierSeed,
      signal: draft.signal,
      overrides: { dob: "01-01-2015" },
    });
    expect(proof.ageAbove18).toBe("0");

    const result = await submitApplication(draft.applicationId, proof);
    expect(result.status).toBe(403);
    expect(result.body.error).toBe("NOT_ELIGIBLE");
  });

  // TC1's concurrency race, covered at the DB level rather than with a
  // second pair of real proofs: UNIQUE(cycle_id, nullifier) is what
  // actually makes two concurrent requests for the same nullifier resolve
  // to exactly one winner (see src/server/intake/submit.ts's comment on
  // its INSERT). Exercising that constraint directly is faster and just as
  // conclusive as generating two more real proofs and racing them over
  // HTTP.
  it("TC1 (race): UNIQUE(cycle_id, nullifier) allows exactly one of two concurrent inserts", async () => {
    const databaseUrl = inject("databaseUrl" as never) as string;
    const cycleId = inject("cycleId" as never) as string;
    const sharedNullifier = `race-${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const idA = randomUUID();
    const idB = randomUUID();

    // Two separate connections, so the two inserts are genuinely concurrent
    // rather than serialized through one client.
    const clientA = new Client({ connectionString: databaseUrl });
    const clientB = new Client({ connectionString: databaseUrl });
    await Promise.all([clientA.connect(), clientB.connect()]);

    const insertOne = (client: Client, id: string) =>
      client.query(
        `INSERT INTO applications (
           id, cycle_id, nullifier, proof_timestamp, age_above18, groth16_proof,
           preferred_name, contact_email, college, course_year, district,
           first_gen, statement
         ) VALUES ($1,$2,$3,$4,true,'{}',$5,$6,$7,$8,$9,$10,$11)`,
        [
          id,
          cycleId,
          sharedNullifier,
          Math.floor(Date.now() / 1000),
          "Race Test Applicant",
          "race@example.com",
          "Test College",
          "B.Sc",
          "Nagpur",
          true,
          "race test row",
        ],
      );

    try {
      const results = await Promise.allSettled([
        insertOne(clientA, idA),
        insertOne(clientB, idB),
      ]);

      const fulfilled = results.filter((r) => r.status === "fulfilled");
      const rejected = results.filter((r) => r.status === "rejected");
      expect(fulfilled).toHaveLength(1);
      expect(rejected).toHaveLength(1);
      const rejectionReason = (rejected[0] as PromiseRejectedResult).reason;
      expect(rejectionReason.code).toBe("23505"); // unique_violation
    } finally {
      // Clean up so this synthetic row doesn't linger in the cycle's real
      // dashboard counts for the rest of the suite.
      await clientA.query(`DELETE FROM applications WHERE id IN ($1, $2)`, [idA, idB]).catch(() => {});
      await Promise.all([clientA.end(), clientB.end()]);
    }
  });

  it("reviews the recorded application end-to-end (shortlist -> award)", async () => {
    // Reuses the application recorded by the very first test in this file
    // instead of generating another real proof just to have something to
    // review.
    const cookie = await loginVolunteer();

    const detailRes = await fetch(
      `${baseUrl()}/api/volunteer/applications/${firstDraftId}`,
      { headers: { cookie } },
    );
    expect(detailRes.status).toBe(200);
    const detail = await detailRes.json();
    expect(detail.preferredName).toBe("Recording Path Success Applicant");
    expect(detail.reviewStatus).toBe("awaiting_review");

    const wrongOriginRes = await fetch(
      `${baseUrl()}/api/volunteer/applications/${firstDraftId}`,
      {
        method: "POST",
        headers: { "content-type": "application/json", cookie, origin: "http://evil.example" },
        body: JSON.stringify({ action: "shortlist", note: "should not apply" }),
      },
    );
    expect(wrongOriginRes.status).toBe(403);

    const shortlistRes = await fetch(
      `${baseUrl()}/api/volunteer/applications/${firstDraftId}`,
      {
        method: "POST",
        headers: { "content-type": "application/json", cookie, origin: baseUrl() },
        body: JSON.stringify({ action: "shortlist", note: "looks strong" }),
      },
    );
    expect(shortlistRes.status).toBe(200);

    const awardRes = await fetch(
      `${baseUrl()}/api/volunteer/applications/${firstDraftId}`,
      {
        method: "POST",
        headers: { "content-type": "application/json", cookie, origin: baseUrl() },
        body: JSON.stringify({ action: "award" }),
      },
    );
    expect(awardRes.status).toBe(200);

    const finalDetailRes = await fetch(
      `${baseUrl()}/api/volunteer/applications/${firstDraftId}`,
      { headers: { cookie } },
    );
    const finalDetail = await finalDetailRes.json();
    expect(finalDetail.reviewStatus).toBe("awarded");
    expect(finalDetail.events.map((e: { action: string }) => e.action)).toEqual([
      "shortlist",
      "award",
    ]);
  });

  // TC6 at the live-server level (schema.test.ts covers this at the unit
  // level too): a body carrying raw-Aadhaar-shaped or validity-flag
  // fields is rejected before any proof is even looked at -- no real proof
  // needed for this one.
  it("TC6/TC3: a body carrying qrData/certificate/claim/valid is rejected without ever reaching verification", async () => {
    const draft = await createDraft();
    const res = await fetch(`${baseUrl()}/api/applications`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        applicationId: draft.applicationId,
        proof: { groth16Proof: {}, valid: true },
        qrData: "9999",
        certificate: "-----BEGIN CERTIFICATE-----",
        claim: { ageAbove18: true },
      }),
    });
    expect(res.status).toBe(400);
  });
});
